import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Ecommercr with convex , clerk , and paystack",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className={cn("h-full antialiased font-sans")}>
      <Navbar />

      <main className="flex-1 pt-8 ">{children}</main>
    </div>
  );
}
